In [59]:
import numpy as np

In [58]:
def algorithme_de_Crout(A):
    n=len(A)
    l=np.eye(n)
    u=np.zeros((n,n))
    u[0,:]=A[0,:]
    l[1:,0]=1/u[0,0]*A[1:,0]
    for k in range(1,n):
        u[k,k:]=A[k,k:]-l[k,:k]@u[:k,k:]
        l[k+1:,k]=1/u[k,k]*(A[k+1:,k]-l[k+1:,:k]@u[:k,k])
    u[n-1,n-1]=A[n-1,n-1]-l[n-1,:n-1]@u[:n-1,n-1]
    return (l,u)

In [60]:
test=np.array([[2,1,1],[1,3,2],[3,2,4]])
a,b=algorithme_de_Crout(test)

In [62]:
#Pour tester le resultat de la fonction algorithme_de_Crout()
a@b

array([[2., 1., 1.],
       [1., 3., 2.],
       [3., 2., 4.]])

# Question n2

In [106]:
# Methode pour la generation de la matrice H_n
def genere_matrice_H(n):
    return np.array([[1/(1+i+j) for i in range(1,n)] for j in range(1,n)])

In [82]:
#Methode de la descente
def descente(l,b):
    n=len(l)
    y=np.zeros(n)
    for i in range(0,n):
        y[i]=(b[i]-sum(l[i,0:i]*y[0:i]))
    return y

In [83]:
#Methode de la remonte
def remonte(u,y):
    n=len(y)
    x=np.zeros(n)
    for i in range(n-1,-1,-1):
        x[i]=(y[i]-sum(u[i,i+1:]*x[i+1:]))/u[i,i]
    return x

In [77]:
#La methode qui fasse la resolution en fesant appel aux methode remote() et descente()
def resolution(h):
    n=len(h)
    b=np.ones(n)
    l,u=algorithme_de_Crout(h)
    y=descente(l,b)
    return remonte(u,y)

In [129]:
resolution(genere_matrice_H(10))

array([ 4.94927192e+02, -1.58379241e+04,  1.80158704e+05, -1.00889938e+06,
        3.15283835e+06, -5.76523319e+06,  6.12559957e+06, -3.50036211e+06,
        8.31340061e+05])

In [128]:
np.linalg.solve(genere_matrice_H(10),np.ones(9))

array([ 4.94941572e+02, -1.58383418e+04,  1.80163050e+05, -1.00892181e+06,
        3.15290331e+06, -5.76534388e+06,  6.12570966e+06, -3.50042124e+06,
        8.31353308e+05])

In [130]:
resolution(genere_matrice_H(50))

array([ 5.81667899e+03, -3.03059848e+05,  5.64867872e+06, -5.19468626e+07,
        2.65594541e+08, -7.84608440e+08,  1.31851796e+09, -1.22136611e+09,
        8.24582675e+08, -6.15672153e+08, -7.98004674e+08,  1.14632579e+09,
        4.44722034e+09, -7.72482696e+09,  7.44318532e+08,  3.91690714e+09,
       -1.42750788e+09,  3.89796378e+08, -2.28383534e+09,  5.06833625e+09,
       -8.43496911e+08, -2.41403841e+09, -1.61867489e+09, -4.68276459e+09,
        5.02248941e+09,  4.18723357e+09,  7.18743906e+07, -3.97701595e+09,
        4.80331863e+09, -5.55584531e+08, -3.65954039e+09, -4.62689541e+09,
        1.95658255e+09,  2.75878095e+09, -2.28628928e+09,  2.90497994e+09,
        4.83434950e+09,  2.39859186e+09, -1.04511529e+10,  8.98961565e+08,
       -3.48515965e+09,  7.43538734e+09, -1.46889121e+09, -1.70920359e+07,
        1.28730579e+09, -3.64786999e+09,  3.78823482e+09, -2.79501401e+09,
        9.62207850e+08])

In [135]:
# La methode de numpy pour tester le resultat
np.linalg.solve(genere_matrice_H(50),np.ones(49))

array([ 2.36538358e+03, -1.31931921e+05,  2.67956613e+06, -2.75297212e+07,
        1.62457164e+08, -5.75438512e+08,  1.18741331e+09, -1.16556678e+09,
       -1.08895377e+08,  7.92955364e+08,  1.00239064e+09, -1.57010974e+09,
       -1.47738614e+09,  3.00746725e+08,  4.81405115e+09, -3.85716551e+08,
       -6.07375867e+09,  5.40280778e+08,  2.64958753e+09, -1.10355778e+08,
        2.68923483e+09, -1.64842077e+09, -1.02836908e+09, -1.26844639e+09,
        6.40647243e+08,  4.89672779e+08,  2.56950904e+08,  8.21989772e+08,
       -1.63045990e+09, -1.30685332e+09,  3.09965837e+09, -3.34016117e+08,
       -1.07855067e+09,  1.65330698e+09,  3.60844309e+08, -8.60031148e+08,
       -2.24809281e+09, -1.05209282e+09,  8.68705085e+08,  3.21229370e+09,
       -1.23237898e+09, -1.13919117e+09,  2.44279743e+09, -2.39684201e+09,
        1.62563473e+09, -9.46362282e+08, -2.85408405e+08,  1.37863623e+08,
        1.98241363e+08])

In [132]:
def errer_quadratique_moyenne():
    n=[2,5,10,20,50,60,70]
    errer=np.zeros(len(n))
    for i in range(len(n)):
        errer[i]=sum((resolution(genere_matrice_H(n[i]))-np.linalg.solve(genere_matrice_H(n[i]),np.ones(n[i]-1)))**2)/len(n)
    return errer

In [133]:
errer_quadratique_moyenne()

array([0.00000000e+00, 3.68867998e-20, 4.68389466e+03, 1.04385064e+17,
       1.09702786e+20, 2.24752639e+20, 9.01796236e+19])

# Remarque:
## Plus la valeur de n augmente plus l'errer devient plus grandre

In [136]:
# Question n3

In [179]:
def algorithme_Cholesky(A):
    n=len(A)
    B=np.zeros((n,n))
    B[0,0]=np.sqrt(A[0,0])
    B[1:,0]=1/B[0,0]*A[1:,0]
    B[0,1:]=B[1:,0]
    for k in range(1,n-1):
        B[k,k]=np.sqrt(A[k,k]-B[k,:k]@B[:k,k])
        B[k+1:,k]=1/B[k,k]*(A[k+1:,k]-B[k+1:,:k]@B[:k,k])
        B[k,k+1:]=B[k+1:,k]
    B[n-1,n-1]=np.sqrt(A[n-1,n-1]-B[n-1,:n-1]@B[:n-1,n-1])
    return B

In [181]:
b=1/2*(genere_matrice_H(5)+genere_matrice_H(5).T)
b

array([[0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [182]:
np.linalg.cholesky(b)

array([[0.57735027, 0.        , 0.        , 0.        ],
       [0.4330127 , 0.1118034 , 0.        , 0.        ],
       [0.34641016, 0.1490712 , 0.02519763, 0.        ],
       [0.28867513, 0.15971914, 0.04724556, 0.00595238]])

In [183]:
algorithme_Cholesky(b)

array([[0.57735027, 0.4330127 , 0.34641016, 0.28867513],
       [0.4330127 , 0.1118034 , 0.1490712 , 0.15971914],
       [0.34641016, 0.1490712 , 0.02519763, 0.04724556],
       [0.28867513, 0.15971914, 0.04724556, 0.00595238]])

In [174]:
np.linalg.cholesky(b)

array([[0.57735027, 0.        , 0.        , 0.        ],
       [0.4330127 , 0.1118034 , 0.        , 0.        ],
       [0.34641016, 0.1490712 , 0.02519763, 0.        ],
       [0.28867513, 0.15971914, 0.04724556, 0.00595238]])