In [1]:
import numpy as np

In [52]:
def algorithme_de_Crout(A):
    n=len(A)
    l=np.eye(n)
    u=np.zeros((n,n))
    u[0,:]=A[0,:]
    l[1:,0]=1/u[0,0]*A[1:,0]
    for k in range(1,n):
        u[k,k:]=A[k,k:]-l[k,:k]@u[:k,k:]
        l[k+1:,k]=1/u[k,k]*(A[k+1:,k]-l[k+1:,:k]@u[:k,k])
    u[n-1,n-1]=A[n-1,n-1]-l[n-1,:n-1]@u[:n-1,n-1]
    return (l,u)

In [53]:
test=np.array([[2,1,1],[1,3,2],[3,2,4]])
a,b=algorithme_de_Crout(test)

In [54]:
a

array([[2. , 1. , 1. ],
       [0. , 2.5, 1.5],
       [0. , 0. , 2.2]])

In [55]:
b@a

array([[2., 1., 1.],
       [1., 3., 2.],
       [3., 2., 4.]])

# Question n2

In [101]:
def descente(l,b):
    n=len(l)
    y=np.zeros(n)
    for i in range(0,n):
        y[i]=(b[i]-sum(l[i,0:i]*y[0:i]))/l[i,i]
    return y

In [102]:
def remonte(u,y):
    n=len(y)
    x=np.zeros(n)
    n=n-1
    x[n]=y[n]/u[n,n]
    for i in range(n-1,-1,-1):
        x[i]=(y[i]-sum(u[i,i+1:]*x[i+1:]))/u[i,i]
    return x

In [103]:
def resolution(h):
    n=len(h)
    b=np.ones(n)
    l,u=algorithme_de_Crout(h)
    y=descente(l,b)
    return remonte(u,y)

In [104]:
def genere_matrice_H(n):
    return np.array([[1/(1+i+j) for i in range(n)] for j in range(n)])

In [105]:
resolution(genere_matrice_H(2))

array([ 1., 12.])

In [99]:
np.linalg.solve(genere_matrice_H(10),np.ones(10))

array([-9.99982337e+00,  9.89984621e+02, -2.37596706e+04,  2.40236992e+05,
       -1.26124560e+06,  3.78374027e+06, -6.72665461e+06,  7.00121663e+06,
       -3.93818664e+06,  9.23772647e+05])